### ISSUE TITLE
vs. leesah/docker-openwrt-dev ?

### ISSUE THREAD

**Issue by peteruithoven** [noonien/docker-openwrt-buildroot#10]
I found that there is also a leesah/docker-openwrt-dev repository, which is published on the docker hub as `openwrt/buildroot` (which looks more official). This repository shared both contributors of this repository (noonien and ddrown), and is updated slightly more recently. 
Which one should I use?

**Comment by noonien** [comment]
Whichever you prefer, I don't believe there's any functional difference. That repo just seems more structured.
