### ISSUE TITLE
Retrieve image? 

### ISSUE THREAD

**Issue by peteruithoven** [noonien/docker-openwrt-buildroot#8]
Probably a noob question, but how does one get the image that's build out of the container? What's the workflow to get it copied to the device? Why not mount a volume?

**Comment by peteruithoven** [comment]
Just figured out one reason for not mounting a volume, OpenWRT only wants to built on case sensitive volumes, and your own disk might not be case sensitive. (It isn't for OS X)

**Comment by peteruithoven** [comment]
Would creating the container with a shared volume, where, after building the image, you copy the image to, work?

**Comment by peteruithoven** [comment]
The people behind WLAN Slovenija mention that I could also use the docker cp command to copy files from a container to my local file system.
See: https://github.com/wlanslovenija/firmware-core#accessing-built-images

**Comment by noonien** [comment]
You could either setup the container so that you can flash the firmware from inside, use the solution I've given in issue #9, or use docker cp.
