### ISSUE TITLE
Why clone OpenWRT inside container?

### ISSUE THREAD

**Issue by peteruithoven** [noonien/docker-openwrt-buildroot#9]
Why clone the OpenWRT source inside the container? The following blog describes a method where he uses a shared volume with the cloned source. 
https://noah.meyerhans.us/blog/2015/03/19/building-openwrt-with-docker/

I don't know which method is better, I'm just curious.

**Comment by noonien** [comment]
It was simply for convenience. If you want you can just [mount a host directory](https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume) unto /home/dev/openwrt.
